//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NacossWebElection.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.CandidateVotes = new HashSet<CandidateVote>();
        }
    
        public string MatNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Sex { get; set; }
        public string email { get; set; }
        public int Position { get; set; }
        public string CurrentLevel { get; set; }
        public decimal Gpa { get; set; }
        public string Manifestor { get; set; }
        public string phoneNo { get; set; }
        public string PhotoUrl { get; set; }
    
        public virtual Position Position1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateVote> CandidateVotes { get; set; }
        public virtual CandidateVoteCount CandidateVoteCount { get; set; }
    }
}
