//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NacossWebElection.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateVote
    {
        public string CandidateMatNo { get; set; }
        public string VoterMatNo { get; set; }
        public int positionID { get; set; }
        public int ID { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual CandidateVoteCount CandidateVoteCount { get; set; }
        public virtual Position Position { get; set; }
        public virtual Voter Voter { get; set; }
    }
}
