//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NacossWebElection.Models.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NacossVotingDBEntities : DbContext
    {
        public NacossVotingDBEntities()
            : base("name=NacossVotingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<CandidateVoteCount> CandidateVoteCounts { get; set; }
        public virtual DbSet<CandidateVote> CandidateVotes { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Voter> Voters { get; set; }
        public virtual DbSet<VoteTime> VoteTimes { get; set; }
    }
}
