//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NacossWebElection.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoteTime
    {
        public Nullable<System.DateTime> VoteTimeStart { get; set; }
        public Nullable<System.DateTime> VoteTimeEnd { get; set; }
        public int sn { get; set; }
    }
}
